---
abstract: 'Perl implementation of JSON-RPC 2.0 protocol for Mojolicious'
author:
  - 'Henry Tang <henryykt@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-JSON-RPC
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 4.74
version: 0.06
